# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

variables:
    azureSubscriptionEndpoint: 42cssSubscription
    azureContainerRegistry: 42css.azurecr.io
    azureResourceGroup: AzureDevOps-Tests
    kubernetesCluster: PixiClusterGitlab
    namespace: pixi

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Docker@2
  displayName: Login to ACR
  inputs:
    command: login
    containerRegistry: azureRegistryConnection

- task: Docker@2
  displayName: Build Pixi App and Push
  inputs:
    command: buildAndPush
    repository: $(azureContainerRegistry)/pixi
    tags: app
    Dockerfile: app/Dockerfile

- task: Kubernetes@1
  displayName: kubectl apply
  inputs:
    connectionType: Azure Resource Manager
    azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
    azureResourceGroup: $(azureResourceGroup)
    azureSubscriptionEndpointForSecrets: $(azureSubscriptionEndpoint)
    kubernetesCluster: $(kubernetesCluster)
    namespace: $(namespace)
    command: apply
    arguments: -f app/deploy/deployment.yaml 
