---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: pixidb
  name: pixidb
spec:
  ports:
  - name: "mongo"
    port: 27017
    targetPort: 27017
  selector:
    app: pixidb
status:
  loadBalancer: {}

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
  labels:
    app: pixidb
    role: runtime
  name: pixidb
spec:
  template:
    metadata:
      labels:
        app: pixidb
    spec:
      containers:
      - name: pixidb
        image: deadrobots/pixi:datastore
        imagePullPolicy: Always
        ports:
          - containerPort: 27017
      restartPolicy: Always
status: {}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pixi
spec:
  selector:
    matchLabels:
      app: pixiapp
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0        # how many pods we can add at a time
      maxUnavailable: 1  # maxUnavailable define how many pods can be unavailable during rolling RollingUpdate
  template:
    metadata:
      labels:
        app: pixiapp
    spec:
      imagePullSecrets:
      - name:  docker-creds
      containers:
      - name: pixiapp
        image: 42css.azurecr.io/42css.azurecr.io/pixi:app
        ports:
          - containerPort: 8000
          - containerPort: 8090
